compressionLevel: mixed

enableGlobalCache: false

packageExtensions:
  "@commitlint/cli@*":
    peerDependencies:
      typescript: ">=4.9.5"
  "@commitlint/load@*":
    dependencies:
      "@types/node": "*"
    peerDependencies:
      typescript: ">=4.9.5"
  "@typescript-eslint/type-utils@*":
    peerDependencies:
      eslint: ^8.57.0 || ^9.0.0
  "@typescript-eslint/utils@*":
    peerDependencies:
      typescript: ">=4.2.0"
  eslint-config-airbnb-typescript@*:
    peerDependencies:
      eslint-plugin-import: ^2.25.2
  eslint-plugin-jsdoc@*:
    dependencies:
      espree: "*"
  typescript-eslint@*:
    peerDependencies:
      eslint: ^8.57.0 || ^9.0.0

pnpEnableEsmLoader: true
